[Definition]
actionstart = 
actionstop = 
actioncheck = 
actionban = curl -s -X POST "https://api.telegram.org/botYOUR_TELEGRAM_BOT_TOKEN/sendMessage" -d parse_mode=HTML -d "chat_id=YOUR_TELEGRAM_CHAT_ID" -d "text=⛔ <b>[VỆ SĨ GÁC CỔNG]</b>%%0AĐã tóm cổ và khóa vĩnh viễn IP lạ: <code><ip></code>%%0ALý do: Cố rà tìm mật khẩu nhà anh." > /dev/null
actionunban = 
